build: bump commons-lang3 to 3.15.0
Spring Cloud Contract 4.2.1 pulls commons-text 1.11.0, which calls
Range.of() added in commons-lang3 3.13.0. Version 3.12.0 pinned in pom
caused NoSuchMethodError in OpenApiContractConverterTest#testRefsInsideArrays.